package com.github.bruce.dao.entity;

import java.util.Date;

public class AEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a.id
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a.c
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    private Integer c;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a.d
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    private Integer d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a.insert_time
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    private Date insertTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a.id
     *
     * @return the value of a.id
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a.id
     *
     * @param id the value for a.id
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a.c
     *
     * @return the value of a.c
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    public Integer getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a.c
     *
     * @param c the value for a.c
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    public void setC(Integer c) {
        this.c = c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a.d
     *
     * @return the value of a.d
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    public Integer getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a.d
     *
     * @param d the value for a.d
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    public void setD(Integer d) {
        this.d = d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a.insert_time
     *
     * @return the value of a.insert_time
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a.insert_time
     *
     * @param insertTime the value for a.insert_time
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}