package com.github.bruce.dao.mapper;

import com.github.bruce.dao.entity.AEntity;
import org.apache.ibatis.annotations.Param;

public interface AEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    int insert(AEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated Sun Jun 16 22:27:34 CST 2019
     */
    int insertSelective(AEntity record);

    AEntity selectById(Integer id);

    int updateById(@Param("id") Integer id, @Param("d") Integer d);
}